language: python
branches:
  only:
  - master
install:
- pip install jupyter pelican
script:
- make html
env:
  global:
    secure: d62xDK6TkeM0n/LVbOKT2hgxQZpTKzR8W4LBhwNOhxImLrdUfeQ/Xz+p214kcluITCf9AfD1dAi8pVgkR4P0WbwRY7kh5McagfyEfSUZ9Z1R6t2MZ6ks9qneHLZ55QMSQFvD1UYNqS76/U3dchCuy315AhLTQcS3prrePs2wyIhpG5Ee3r5VU3y1W2KtxLuKvBA2to/cjSpy2k1AysJ/fx7ZTCxw3ESY4suBqlviGVDAEkNey8mTDSzAXuML53likCpYrq1QfxNARGdVmb8k6Ge17+s97OLRRbgAd4wzGHotAfrpNitQxuo6lj8FoJUHQCz/aseClLQbVKc1gbYnTjcUK2HGpZTlYEH6H1ttV7Ei/mC1AzSy2UuzJsR99FkW3Zj2egGFri8M6DEKi5AB/4fGIkmq9RiGNElC+TKAb102yuc1KMX6WuYQ2A7PHd+BuJ3ZfKV5Gq2CoWZ0d538CyFyx5T0Mcc/8uYVPbmL2CzWc27tv4PAtjqWXeQdFeJpPILZabhJ10H02qFWuNqcNoTcgBTNxYrM8FDLB9gFK2mu+ca5zwA1GTbeZMrZ3kWCPMKfI6K/B8+BzfLqTasUfi0RCcw61g0pp+/SiN3L3WBuzKZKK4NuIhK4Fp4kkvv2ZxXBD6nrUz0FxId0MnvMn+e1EZeuHoeGPaCZEB04hsc=
after_success: bash deploy.sh